//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeWith1C.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int RestDispatch { get; set; }
        public string TransCompany { get; set; }
        public string TransContactName { get; set; }
        public string TransAdress { get; set; }
        public string TransPhone { get; set; }
        public string ReciverAdress { get; set; }
        public string ReciverContactName { get; set; }
        public string ReciverPhone { get; set; }
        public string Comment { get; set; }
    }
}
