//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeWith1C.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class developer_database : DbContext
    {
        public developer_database()
            : base("name=developer_database")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Firms> Firms { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<ManagerRecovery> ManagerRecovery { get; set; }
        public DbSet<MessageFiles> MessageFiles { get; set; }
        public DbSet<Messages> Messages { get; set; }
        public DbSet<Partners> Partners { get; set; }
        public DbSet<Settings> Settings { get; set; }
        public DbSet<StorageDeliveryStatus> StorageDeliveryStatus { get; set; }
        public DbSet<StorageDrivers> StorageDrivers { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<PriceColumns> PriceColumns { get; set; }
        public DbSet<Goods> Goods { get; set; }
        public DbSet<Deliveries> Deliveries { get; set; }
        public DbSet<Suppliers> Suppliers { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Exchange1C> Exchange1C { get; set; }
        public DbSet<Exchange1CBroken> Exchange1CBroken { get; set; }
        public DbSet<OrderItems> OrderItems { get; set; }
        public DbSet<PricesPersonal> PricesPersonal { get; set; }
        public DbSet<PartnerRests> PartnerRests { get; set; }
        public DbSet<PriceColumnItem> PriceColumnItem { get; set; }
    }
}
