//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeWith1C.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange1C
    {
        public int Id { get; set; }
        public int Source { get; set; }
        public int ExchangeState { get; set; }
        public System.DateTime Date { get; set; }
        public int ItemId { get; set; }
    }
}
