//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeWith1C.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Code1C { get; set; }
        public int CategoryId { get; set; }
        public bool IsDeleted { get; set; }
        public string PR { get; set; }
        public short GroupCount { get; set; }
        public float Weight { get; set; }
        public float Volume { get; set; }
        public int Barcode { get; set; }
        public string ImageUrl { get; set; }
    }
}
