//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeWith1C.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public int Type { get; set; }
        public Nullable<int> UserSenderId { get; set; }
        public int UserReciverId { get; set; }
        public string Head { get; set; }
        public string Body { get; set; }
    }
}
