//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeWith1C.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string Code1C { get; set; }
        public int Status { get; set; }
        public int SuppliersId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public System.DateTime ReservDate { get; set; }
        public int PayType { get; set; }
        public int FirmId { get; set; }
        public string CommentForStorage { get; set; }
    }
}
