//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeWith1C.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Rang { get; set; }
        public string CompanyName { get; set; }
        public string AdressMap { get; set; }
        public Nullable<double> AdressLatitude { get; set; }
        public Nullable<double> AdressLongitude { get; set; }
        public string Num1C { get; set; }
        public int Status { get; set; }
        public double DebtBank { get; set; }
        public Nullable<double> DebtCash { get; set; }
        public string ContactName { get; set; }
        public string ContactPhoneMobile { get; set; }
        public string ContactPhoneJob { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public int PriceColumnId { get; set; }
        public int DeclaredPriceColumnId { get; set; }
        public Nullable<System.DateTime> Trial { get; set; }
        public bool OnSite { get; set; }
    }
}
