//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeWith1C.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageDeliveryStatus
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDelivery { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string Comment { get; set; }
    }
}
