//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeWith1C.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int Role { get; set; }
        public string Login { get; set; }
        public string HashPass { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Fio { get; set; }
    }
}
